### ISSUE TITLE
Permission to use

### ISSUE THREAD

**Issue by vinylrain** [kaivi/ReactInlineEdit#1]
What sort of permission do we have to use this? Any licenses?

**Comment by kaivi** [comment]
Ugh, the license in package.json is MIT, but one included in ./LICENSE is GNU GPL v2.0.
MIT is the correct one, and I will change contents of LICENSE with the new version: can't publish to NPM without changing version number, and not sure if changing version number is appropriate here. `sorry, I am not good with computers`
