### ISSUE TITLE
Successor project ?

### ISSUE THREAD

**Issue by asaf** [kaivi/ReactInlineEdit#13]
Hey!

Seeking for inline edit with more capabilities, I found what I need in your new project,
Any chance to expose its current early stage ? (End of feb is too late and i'm the other alternatives are not nice as yours!)

Thanks! =)

**Comment by masad-frost** [comment]
+1

It looks complete to me in the demo. :checkered_flag:

**Comment by kaivi** [comment]
Hey, sorry for the long delay, I've published it now [at npm](https://www.npmjs.com/package/riek).
