### ISSUE TITLE
automatically focusing on InlineEdit field

### ISSUE THREAD

**Issue by Robinnnnn** [kaivi/ReactInlineEdit#14]
I'd like to have the browser automatically focus on the InlineEdit field to make it more obvious to the user that the field is editable.

Using React's built-in [autoFocus](http://stackoverflow.com/a/28891210/5377437) param does not work: 
`<InlineEdit autoFocus text="Untitled Project" paramName="title" change={editTitle} />`.

For now I'm using a compromise by [finding the specific DOMNode on componentDidMount](http://stackoverflow.com/a/28890330/5377437):
```
componentDidMount() {
	ReactDOM.findDOMNode(this.refs.title).focus();
}
render() {
	const {editTitle} = this.props;
	return (
		<InlineEdit ref="title" text="Untitled Project" paramName="title" change={editTitle} />
	)
}
```

While the workaround isn't necessarily difficult to implement, I'd prefer the InlineEdit component be compatible with `autoFocus`. No worries if this is too difficult to implement, huge fan of this library otherwise!

**Comment by masad-frost** [comment]
This should be easy to implement I think.

```
...
static propTypes = {
  ...
  autoFocus: React.PropTypes.bool,
}
...
componentDidMount() {
  if (this.props.autoFocus) {
      this.startEditing();
  }
}
...
```
Then you set `<InlineEdit autoFocus={true}  .../>`

Should work, as long as you don't have an element that steals the focus after.

**Comment by Robinnnnn** [comment]
@masad-frost this is a great idea, much appreciated
