### ISSUE TITLE
Warning: Unknown prop `onReturn` on <input> tag. Remove this prop from the element. 

### ISSUE THREAD

**Issue by sajumani** [kaivi/ReactInlineEdit#24]
Hi,

am getting error, when i try to edit,
Warning: Unknown prop `onReturn` on <input> tag. Remove this prop from the element.

**Comment by keown** [comment]
still having the issue with `1.0.7` and react `15.0.1`

**Comment by jwyuen** [comment]
I'm also having this issue on 1.0.7 and React 15.3.1

**Comment by evashchuk** [comment]
Also having the same issue

**Comment by ismyrnow** [comment]
Can you bump the bugfix version and republish to npm?

**Comment by kaivi** [comment]
I've updated it now, not sure what happened there. You should try [Riek](https://github.com/kaivi/riek) instead of this repo, I've switched to it months ago.
