### ISSUE TITLE
What's the point of paramName

### ISSUE THREAD

**Issue by masad-frost** [kaivi/ReactInlineEdit#8]
I was wondering, why did you take that approach? Passing an object with key `paramName` and value `state.text` to the `change` function? https://github.com/kaivi/ReactInlineEdit/blob/master/index.jsx#L43-L48

As opposed to just doing `this.props.change(this.state.text)`?

**Comment by kaivi** [comment]
This was meant for a usage scenario with reducers, so that one could just pass edited chunk of text to a reducer function, which combines previous state and a new chunk using a spread operator, like so:
```javascript
reduce = (state, newData) => {
   return {...state, ...newData};
}
```
I suppose it is handy when using Redux or even Relay+GraphQL mutations.

**Comment by masad-frost** [comment]
Makes sense, thanks.
